// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI-powered dynamic form generation for incident reports. 
 *
 * - generateIncidentForm - A function that generates a dynamic form based on the incident type.
 * - GenerateIncidentFormInput - The input type for the generateIncidentForm function.
 * - GenerateIncidentFormOutput - The return type for the generateIncidentForm function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateIncidentFormInputSchema = z.object({
  incidentType: z.string().describe('The type of incident for which to generate the form.'),
});

export type GenerateIncidentFormInput = z.infer<typeof GenerateIncidentFormInputSchema>;

const GenerateIncidentFormOutputSchema = z.object({
  formSchema: z.string().describe('A JSON schema representing the dynamic form for the specified incident type.'),
  uiSchema: z.string().describe('A JSON schema representing the UI configuration for the form.'),
});

export type GenerateIncidentFormOutput = z.infer<typeof GenerateIncidentFormOutputSchema>;

export async function generateIncidentForm(input: GenerateIncidentFormInput): Promise<GenerateIncidentFormOutput> {
  return generateIncidentFormFlow(input);
}

const generateIncidentFormPrompt = ai.definePrompt({
  name: 'generateIncidentFormPrompt',
  input: {schema: GenerateIncidentFormInputSchema},
  output: {schema: GenerateIncidentFormOutputSchema},
  prompt: `You are an expert form designer specializing in incident reports.

You will generate a JSON schema for a dynamic form and a corresponding UI schema based on the incident type provided. Ensure the generated form includes relevant fields and follows a clear and logical structure.

Incident Type: {{{incidentType}}}

Form Schema (JSON):
UI Schema (JSON):`,
});

const generateIncidentFormFlow = ai.defineFlow(
  {
    name: 'generateIncidentFormFlow',
    inputSchema: GenerateIncidentFormInputSchema,
    outputSchema: GenerateIncidentFormOutputSchema,
  },
  async input => {
    const {output} = await generateIncidentFormPrompt(input);
    return output!;
  }
);
